name: Reusable Workflow
on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      confirmation:
        type: boolean
        description: "Please confirm that you need to set the HTML page after this pipeline runs manually"
        required: true
      environment:
        type: choice
        description: "Select deployment environment"
        options:
          - staging
          - production

env:
  GITHUB_RUN_ID: $GITHUB_RUN_ID

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "env: $env"
          echo "GitHub Run ID: $GITHUB_RUN_ID"
        env:
          env: ${{ inputs.environment }}
